<a href="https://colab.research.google.com/github/sabrinaangel/ml-dataset-preprocessing/blob/main/python2/tree/DecisionTree_IrisCSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Import library numpy, pandas dan scikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [4]:
#Membaca Dataset dari File ke Pandas dataFrame
irisDataset = pd.read_csv('Dataset Iris.csv', delimiter=';', header=0)

In [5]:
irisDataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             100 non-null    int64
 1   SepalLengthCm  100 non-null    float64
 2   SepalWidthCm   100 non-null    float64
 3   PetalLengthCm  100 non-null    float64
 4   PetalWidthCm   100 non-null    float64
 5   Species        100 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 4.8+ KB

In [6]:
irisDataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,7.00,3.02,4.07,1.04,Iris-versicolor
1,2,6.04,3.02,4.05,1.05,Iris-versicolor
2,3,6.09,3.01,4.09,1.05,Iris-versicolor
3,4,5.05,2.03,4.00,1.03,Iris-versicolor
4,5,6.05,2.08,4.06,1.05,Iris-versicolor
...,...,...,...,...,...,...
95,96,6.07,3.00,5.02,2.03,Iris-virginica
96,97,6.03,2.05,5.00,1.09,Iris-virginica
97,98,6.05,3.00,5.02,2.00,Iris-virginica
98,99,6.02,3.04,5.04,2.03,Iris-virginica
99,100,5.09,3.00,5.01,1.08,Iris-virginica

In [7]:
#Mengubah kelas (kolom "Species") dari String ke Unique-Integer
irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

In [8]:
irisDataset

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1           7.00          3.02           4.07          1.04        0
1     2           6.04          3.02           4.05          1.05        0
2     3           6.09          3.01           4.09          1.05        0
3     4           5.05          2.03           4.00          1.03        0
4     5           6.05          2.08           4.06          1.05        0
..  ...            ...           ...            ...           ...      ...
95   96           6.07          3.00           5.02          2.03        1
96   97           6.03          2.05           5.00          1.09        1
97   98           6.05          3.00           5.02          2.00        1
98   99           6.02          3.04           5.04          2.03        1
99  100           5.09          3.00           5.01          1.08        1

[100 rows x 6 columns]

In [9]:
#Menghapus kolom "Id"
irisDataset = irisDataset.drop(labels="Id", axis=1)

In [10]:
irisDataset

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            7.00          3.02           4.07          1.04        0
1            6.04          3.02           4.05          1.05        0
2            6.09          3.01           4.09          1.05        0
3            5.05          2.03           4.00          1.03        0
4            6.05          2.08           4.06          1.05        0
..            ...           ...            ...           ...      ...
95           6.07          3.00           5.02          2.03        1
96           6.03          2.05           5.00          1.09        1
97           6.05          3.00           5.02          2.00        1
98           6.02          3.04           5.04          2.03        1
99           5.09          3.00           5.01          1.08        1

[100 rows x 5 columns]

In [11]:
#Mengubah dataFrame ke array Numpy
irisDataset = irisDataset.to_numpy()

In [12]:
#Membagi Dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]),
                             axis=0)

In [13]:
#Memecah Dataset ke Input dan Label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]

In [14]:
inputTesting

array([[5.05, 2.06, 4.04, 1.02],
       [6.01, 3.  , 4.06, 1.04],
       [5.08, 2.06, 4.  , 1.02],
       [5.  , 2.03, 3.03, 1.  ],
       [5.06, 2.07, 4.02, 1.03],
       [5.07, 3.  , 4.02, 1.02],
       [5.07, 2.09, 4.02, 1.03],
       [6.02, 2.09, 4.03, 1.03],
       [5.01, 2.05, 3.  , 1.01],
       [5.07, 2.08, 4.01, 1.03],
       [6.07, 3.01, 5.06, 2.04],
       [6.09, 3.01, 5.01, 2.03],
       [5.08, 2.07, 5.01, 1.09],
       [6.08, 3.02, 5.09, 2.03],
       [6.07, 3.03, 5.07, 2.05],
       [6.07, 3.  , 5.02, 2.03],
       [6.03, 2.05, 5.  , 1.09],
       [6.05, 3.  , 5.02, 2.  ],
       [6.02, 3.04, 5.04, 2.03],
       [5.09, 3.  , 5.01, 1.08]])

In [15]:
#Mendefinisikan Decision Tree Classifier
model = tree.DecisionTreeClassifier()

In [16]:
#Mentraining Model
model = model.fit(inputTraining, labelTraining)

In [17]:
#Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi   : ", hasilPrediksi)

Label Sebenarnya :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Hasil Prediksi   :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [18]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 20 data
Prediksi Salah : 0 data
Akurasi : 100.0 %